---
language: cpp

sudo: required

compiler:
  - gcc
  
os:
  - linux

before_install:
  - echo $LANG
  - echo $LC_ALL
  - git submodule update --init
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install qt5-default libqt5websockets5-dev libqt5x11extras5-dev libgcrypt20-dev zlib1g-dev libx11-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install qt5 libgcrypt libgpg-error zlib; fi
script:
  - if [ $TRAVIS_OS_NAME == linux ]; then qmake client/client.pro && make; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then /usr/local/opt/qt5/bin/qmake client/client.pro && /usr/local/opt/qt5/bin/qmake client/client.pro; fi

notifications:
  email:
  - niklaus.giger@member.fsf.org

